version: '3.8'
services:
  nextjs:
    container_name: nextjs-f1webapp
    build: .
    ports:
      - "3100:3100"
    restart: always
    working_dir: /usr/app
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
    networks:
      - f1-network

networks:
  f1-network:
    external: true
